export const CONTACT_ACTIONS = {
  CREATE: "CREATE_CONTACT",
  DELETE: "DELETE_CONTACT",
};

export const EDITOR_ACTIONS = {
  CHANGE_NAME: "CHANGE_NAME",
  CHANGE_EMAIL: "CHANGE_EMAIL",
  RESET: "RESET",
};
